repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: []
        args: ["--line-length=100"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies: []
  - repo: https://github.com/pycqa/pylint
    rev: v3.2.6
    hooks:
      - id: pylint
        name: pylint (src)
        entry: pylint
        language: python
        types: [python]
        args: ["src", "tests", ""]
        additional_dependencies: []
  - repo: local
    hooks:
      - id: pytest
        name: pytest (unit/integration)
        entry: pytest -q --maxfail=1 --disable-warnings
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]
