name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test-lint:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends             libkeyutils-dev build-essential

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project (build extension)
        run: pip install -e .

      - name: Install test and lint tooling
        run: |
          pip install pytest pytest-cov flake8 flake8-pyproject pylint mypy

      - name: Lint (flake8)
        run: |
          flake8 src tests

      - name: Lint (pylint)
        run: |
          pylint src/linux_keyring tests 
        # NOTE: set  to avoid failing the entire build initially if there are many warnings.
        # Change to strict by removing  once clean.
        #
      - name: Type checking (mypy)
        run: |
          mypy src tests

      - name: Run tests
        run: |
          pytest -q --maxfail=1 --disable-warnings

